server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://mysql:3306/orderdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ecommerce.orderservice.event.PaymentEvent

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

services:
  product-service:
    url: http://product-service:8082

kafka:
  topics:
    order-placed: order-placed
    payment-confirmed: payment-confirmed
    payment-failed: payment-failed
  consumer:
    group-id: order-service-group